services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./service:/service
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=password
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=password
  redis:
    image: redis:7.0.5-alpine
    hostname: redis


  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    volumes:
      - ./service:/service
    command: -A celery_app.app worker --loglevel=info
    links:
      - redis
    depends_on:
      - redis
      - database
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=password


  flower:
    build:
      context: .
    hostname: flower
    entrypoint: celery
    volumes:
      - ./service:/service
    command: -A celery_app.app flower
    ports:
      - "5555:5555"
    links:
      - redis
    depends_on:
      - redis





